service: omicas
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - timestream:WriteRecords
      Resource: arn:aws:timestream:*:*:database/omicas-device-table-test-tesis/table/omicas-device-table


plugins:
 - serverless-offline
 
resources:
  Resources:
    MyDatabase:
      Type: 'AWS::Timestream::Database'
      Properties:
        DatabaseName: omicas-device-database
          
    MyTimestreamTable:
      Type: "AWS::Timestream::Table"
      Properties:
        DatabaseName: "omicas-device-database"
        TableName: "omicas-device-table"
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: '24'
          MagneticStoreRetentionPeriodInDays: '7'
        Tags:
          - Key: "Name"
            Value: "omicas-device-table"
functions:
  hello:
    handler: 'src/functions/handler.hello'
    events:
      - http:
          method: get
          path: hello
  insert:
    handler: 'src/functions/handler.insert'
    events:
      - timestream:
          dimensions:
            - Name: 'measurement'
              Value: 'String'
            - Name: 'ubicacion'
              Value: 'String'
            - Name: 'dispositivo'
              Value: 'String'
            - Name: 'DeviceEUI'
              Value: 'String'
          measureName: 'VBatt'
          measureValue: '$.VBatt'
          measureTime: '$.time'
          databaseName: 'omicas-device-table-test-tesis'
          tableName: 'omicas-device-table'
          
