service: omicas
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - timestream:WriteRecords
      Resource: arn:aws:timestream:*:*:database/my-database-name/table/my-table-name


plugins:
 - serverless-offline
 - serverless-iam-roles-per-function
 
resources:
  Resources:
    MyTimestreamDatabase:
      Type: "AWS::Timestream::Database"
      Properties:
        DatabaseName: "my-database-name"
        Tags:
          - Key: "Name"
            Value: "my-database-name"
          
    MyTimestreamTable:
      Type: "AWS::Timestream::Table"
      Properties:
        DatabaseName: "my-database-name"
        TableName: "my-table-name"
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: '24'
          MagneticStoreRetentionPeriodInDays: '7'
        Tags:
          - Key: "Name"
            Value: "my-table-name"
functions:
  hello:
    handler: 'src/functions/handler.hello'
    events:
      - http:
          method: get
          path: hello
  insert:
    handler: 'src/functions/handler.insert'
    events:
      - timestream:
          dimensions:
            - Name: 'measurement'
              Value: 'String'
            - Name: 'ubicacion'
              Value: 'String'
            - Name: 'dispositivo'
              Value: 'String'
            - Name: 'DeviceEUI'
              Value: 'String'
          measureName: 'VBatt'
          measureValue: '$.VBatt'
          measureTime: '$.time'
          databaseName: 'my-database-name'
          tableName: 'my-table-name'
          
