service: omicas
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - timestream:*
      Resource: arn:aws:timestream:*:*:database/omicas-device-database/table/omicas-device-table
    - Effect: Allow
      Action:
        - timestream:*
      Resource: "*"

plugins:
 - serverless-offline
 
resources:
  Resources:
    MyDatabase:
      Type: 'AWS::Timestream::Database'
      Properties:
        DatabaseName: omicas-device-database
          
    MyTimestreamTable:
      Type: "AWS::Timestream::Table"
      Properties:
        DatabaseName: "omicas-device-database"
        TableName: "omicas-device-table"
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: '24'
          MagneticStoreRetentionPeriodInDays: '7'
        Tags:
          - Key: "Name"
            Value: "omicas-device-table"
# arn:aws:lambda:us-east-1:280184369463:function:omicas-dev-insert
functions:
  hello:
    handler: 'src/functions/handler.hello'
    events:
      - http:
          method: get
          path: hello
  insert:
    handler: 'src/functions/handler.insert'



