service: omicas
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - timestream:*
          Resource: arn:aws:timestream:*:*:database/omicas-device-database/table/omicas-device-table
        - Effect: Allow
          Action:
            - timestream:*
          Resource: "*"

plugins:
 - serverless-offline
 - serverless-plugin-typescript
 
resources:
  Resources:
    MyDatabase:
      Type: 'AWS::Timestream::Database'
      Properties:
        DatabaseName: omicas-device-database
          
    MyTimestreamTable:
      Type: "AWS::Timestream::Table"
      DependsOn: MyDatabase
      Properties:
        DatabaseName: "omicas-device-database"
        TableName: "omicas-device-table"
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: '24'
          MagneticStoreRetentionPeriodInDays: '7'
        Tags:
          - Key: "Name"
            Value: "omicas-device-table"

functions:
  pushDecodeIntoInfluxDB:
    handler: 'src/functions/influxDbFunctions.pushInfluxDb'
    events:
      - http:
          method: get
          path: pushDecodeIntoInfluxDB
  decodeFunction:
    handler: 'src/functions/decodeFunctions.handler'
    events:
      - http:
          method: post
          path: decodeFunction
  insertIntoTimeStream:
    handler: 'src/functions/influxDbFunctions.insert'
    events:
      - http:
          method: get
          path: insertIntoTimeStream



